local RZY_Library = {}

function RZY_Library:MakeWindow(TitleText)
    -- PERBAIKAN: Deteksi lokasi GUI yang aman untuk Executor HP / Mobile
    local TargetGui
    pcall(function()
        TargetGui = (gethui and gethui()) or game:GetService("CoreGui")
    end)
    if not TargetGui then
        TargetGui = game:GetService("Players").LocalPlayer:WaitForChild("PlayerGui")
    end
    
    if TargetGui:FindFirstChild("RZY_Hub") then
        TargetGui.RZY_Hub:Destroy()
    end

    local ScreenGui = Instance.new("ScreenGui")
    ScreenGui.Name = "RZY_Hub"
    [span_2](start_span)ScreenGui.Parent = TargetGui[span_2](end_span)

    local RZYIcon = Instance.new("TextButton")
    [span_3](start_span)RZYIcon.Size = UDim2.new(0, 50, 0, 50)[span_3](end_span)
    [span_4](start_span)RZYIcon.Position = UDim2.new(0.5, -25, 0, 20)[span_4](end_span)
    [span_5](start_span)RZYIcon.BackgroundColor3 = Color3.fromRGB(15, 15, 15)[span_5](end_span)
    [span_6](start_span)RZYIcon.Text = "R Z Y"[span_6](end_span)
    [span_7](start_span)RZYIcon.TextColor3 = Color3.fromRGB(0, 170, 255)[span_7](end_span)
    [span_8](start_span)RZYIcon.TextSize = 13[span_8](end_span)
    [span_9](start_span)RZYIcon.Font = Enum.Font.Gotham[span_9](end_span)
    [span_10](start_span)RZYIcon.Visible = false[span_10](end_span)
    [span_11](start_span)RZYIcon.Active = true[span_11](end_span)
    [span_12](start_span)RZYIcon.Draggable = true[span_12](end_span)
    [span_13](start_span)RZYIcon.Parent = ScreenGui[span_13](end_span)

    [span_14](start_span)Instance.new("UICorner", RZYIcon).CornerRadius = UDim.new(1, 0)[span_14](end_span)
    [span_15](start_span)local IconStroke = Instance.new("UIStroke", RZYIcon)[span_15](end_span)
    [span_16](start_span)IconStroke.Color = Color3.fromRGB(0, 170, 255)[span_16](end_span)
    [span_17](start_span)IconStroke.Thickness = 1.5[span_17](end_span)

    local MainFrame = Instance.new("Frame")
    [span_18](start_span)MainFrame.Size = UDim2.new(0, 300, 0, 450)[span_18](end_span)
    [span_19](start_span)MainFrame.Position = UDim2.new(0.5, -150, 0.5, -225)[span_19](end_span)
    [span_20](start_span)MainFrame.BackgroundColor3 = Color3.fromRGB(20, 20, 20)[span_20](end_span)
    [span_21](start_span)MainFrame.BorderSizePixel = 0[span_21](end_span)
    [span_22](start_span)MainFrame.Active = true[span_22](end_span)
    [span_23](start_span)MainFrame.Draggable = true[span_23](end_span)
    [span_24](start_span)MainFrame.Parent = ScreenGui[span_24](end_span)

    [span_25](start_span)Instance.new("UICorner", MainFrame).CornerRadius = UDim.new(0, 8)[span_25](end_span)
    [span_26](start_span)local MainStroke = Instance.new("UIStroke", MainFrame)[span_26](end_span)
    [span_27](start_span)MainStroke.Color = Color3.fromRGB(0, 170, 255)[span_27](end_span)
    [span_28](start_span)MainStroke.Thickness = 1.5[span_28](end_span)

    local TopBar = Instance.new("Frame")
    [span_29](start_span)TopBar.Size = UDim2.new(1, 0, 0, 40)[span_29](end_span)
    [span_30](start_span)TopBar.BackgroundColor3 = Color3.fromRGB(10, 10, 10)[span_30](end_span)
    [span_31](start_span)TopBar.Parent = MainFrame[span_31](end_span)
    [span_32](start_span)Instance.new("UICorner", TopBar).CornerRadius = UDim.new(0, 8)[span_32](end_span)

    local TopCover = Instance.new("Frame")
    [span_33](start_span)TopCover.Size = UDim2.new(1, 0, 0, 10)[span_33](end_span)
    [span_34](start_span)TopCover.Position = UDim2.new(0, 0, 1, -10)[span_34](end_span)
    [span_35](start_span)TopCover.BackgroundColor3 = Color3.fromRGB(10, 10, 10)[span_35](end_span)
    [span_36](start_span)TopCover.BorderSizePixel = 0[span_36](end_span)
    [span_37](start_span)TopCover.Parent = TopBar[span_37](end_span)

    local Title = Instance.new("TextLabel")
    [span_38](start_span)Title.Size = UDim2.new(1, -90, 1, 0)[span_38](end_span)
    [span_39](start_span)Title.Position = UDim2.new(0, 15, 0, 0)[span_39](end_span)
    [span_40](start_span)Title.BackgroundTransparency = 1[span_40](end_span)
    [span_41](start_span)Title.Text = TitleText[span_41](end_span)
    [span_42](start_span)Title.TextColor3 = Color3.fromRGB(0, 170, 255)[span_42](end_span)
    [span_43](start_span)Title.Font = Enum.Font.GothamBold[span_43](end_span)
    [span_44](start_span)Title.TextSize = 16[span_44](end_span)
    [span_45](start_span)Title.TextXAlignment = Enum.TextXAlignment.Left[span_45](end_span)
    [span_46](start_span)Title.Parent = TopBar[span_46](end_span)

    local CloseBtn = Instance.new("TextButton")
    [span_47](start_span)CloseBtn.Size = UDim2.new(0, 30, 0, 30)[span_47](end_span)
    [span_48](start_span)CloseBtn.Position = UDim2.new(1, -35, 0, 5)[span_48](end_span)
    [span_49](start_span)CloseBtn.BackgroundTransparency = 1[span_49](end_span)
    [span_50](start_span)CloseBtn.Text = "X"[span_50](end_span)
    [span_51](start_span)CloseBtn.TextColor3 = Color3.fromRGB(255, 50, 50)[span_51](end_span)
    [span_52](start_span)CloseBtn.Font = Enum.Font.GothamBold[span_52](end_span)
    [span_53](start_span)CloseBtn.TextSize = 16[span_53](end_span)
    [span_54](start_span)CloseBtn.Parent = TopBar[span_54](end_span)

    local MinBtn = Instance.new("TextButton")
    [span_55](start_span)MinBtn.Size = UDim2.new(0, 30, 0, 30)[span_55](end_span)
    [span_56](start_span)MinBtn.Position = UDim2.new(1, -70, 0, 5)[span_56](end_span)
    [span_57](start_span)MinBtn.BackgroundTransparency = 1[span_57](end_span)
    [span_58](start_span)MinBtn.Text = "-"[span_58](end_span)
    [span_59](start_span)MinBtn.TextColor3 = Color3.fromRGB(255, 255, 255)[span_59](end_span)
    [span_60](start_span)MinBtn.Font = Enum.Font.GothamBold[span_60](end_span)
    [span_61](start_span)MinBtn.TextSize = 24[span_61](end_span)
    [span_62](start_span)MinBtn.Parent = TopBar[span_62](end_span)

    local Container = Instance.new("ScrollingFrame")
    [span_63](start_span)Container.Size = UDim2.new(1, -20, 1, -55)[span_63](end_span)
    [span_64](start_span)Container.Position = UDim2.new(0, 10, 0, 45)[span_64](end_span)
    [span_65](start_span)Container.BackgroundTransparency = 1[span_65](end_span)
    [span_66](start_span)Container.ScrollBarThickness = 2[span_66](end_span)
    [span_67](start_span)Container.ScrollBarImageColor3 = Color3.fromRGB(0, 170, 255)[span_67](end_span)
    [span_68](start_span)Container.Parent = MainFrame[span_68](end_span)

    [span_69](start_span)local UIListLayout = Instance.new("UIListLayout")[span_69](end_span)
    [span_70](start_span)UIListLayout.Padding = UDim.new(0, 8)[span_70](end_span)
    [span_71](start_span)UIListLayout.HorizontalAlignment = Enum.HorizontalAlignment.Center[span_71](end_span)
    [span_72](start_span)UIListLayout.Parent = Container[span_72](end_span)

    UIListLayout:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()
        [span_73](start_span)Container.CanvasSize = UDim2.new(0, 0, 0, UIListLayout.AbsoluteContentSize.Y + 1000)[span_73](end_span)
    end)

    [span_74](start_span)CloseBtn.MouseButton1Click:Connect(function() ScreenGui:Destroy() end)[span_74](end_span)
    [span_75](start_span)MinBtn.MouseButton1Click:Connect(function() MainFrame.Visible = false RZYIcon.Visible = true end)[span_75](end_span)
    [span_76](start_span)RZYIcon.MouseButton1Click:Connect(function() MainFrame.Visible = true RZYIcon.Visible = false end)[span_76](end_span)

    local WindowElements = {}

    function WindowElements:AddLabel(Text)
        [span_77](start_span)local LabelFrame = Instance.new("Frame")[span_77](end_span)
        [span_78](start_span)LabelFrame.Size = UDim2.new(1, -10, 0, 30)[span_78](end_span)
        [span_79](start_span)LabelFrame.BackgroundColor3 = Color3.fromRGB(25, 25, 25)[span_79](end_span)
        [span_80](start_span)LabelFrame.Parent = Container[span_80](end_span)

        [span_81](start_span)Instance.new("UICorner", LabelFrame).CornerRadius = UDim.new(0, 5)[span_81](end_span)
        [span_82](start_span)local LabelStroke = Instance.new("UIStroke", LabelFrame)[span_82](end_span)
        [span_83](start_span)LabelStroke.Color = Color3.fromRGB(0, 100, 150)[span_83](end_span)
        [span_84](start_span)LabelStroke.Thickness = 1[span_84](end_span)

        [span_85](start_span)local TextLabel = Instance.new("TextLabel")[span_85](end_span)
        [span_86](start_span)TextLabel.Size = UDim2.new(1, -20, 1, 0)[span_86](end_span)
        [span_87](start_span)TextLabel.Position = UDim2.new(0, 10, 0, 0)[span_87](end_span)
        [span_88](start_span)TextLabel.BackgroundTransparency = 1[span_88](end_span)
        [span_89](start_span)TextLabel.Text = Text[span_89](end_span)
        [span_90](start_span)TextLabel.TextColor3 = Color3.fromRGB(200, 200, 200)[span_90](end_span)
        [span_91](start_span)TextLabel.Font = Enum.Font.Gotham[span_91](end_span)
        [span_92](start_span)TextLabel.TextSize = 12[span_92](end_span)
        [span_93](start_span)TextLabel.TextWrapped = true[span_93](end_span)
        [span_94](start_span)TextLabel.TextXAlignment = Enum.TextXAlignment.Center[span_94](end_span)
        [span_95](start_span)TextLabel.Parent = LabelFrame[span_95](end_span)

        [span_96](start_span)local LabelHandler = {}[span_96](end_span)
        [span_97](start_span)function LabelHandler:Set(NewText)[span_97](end_span)
            [span_98](start_span)TextLabel.Text = NewText[span_98](end_span)
        [span_99](start_span)end[span_99](end_span)
        [span_100](start_span)return LabelHandler[span_100](end_span)
    end

    [span_101](start_span)function WindowElements:AddDropdown(Text, Options, Callback)[span_101](end_span)
        [span_102](start_span)local DropdownFrame = Instance.new("Frame")[span_102](end_span)
        [span_103](start_span)DropdownFrame.Size = UDim2.new(1, -10, 0, 35)[span_103](end_span)
        [span_104](start_span)DropdownFrame.BackgroundColor3 = Color3.fromRGB(30, 30, 30)[span_104](end_span)
        [span_105](start_span)DropdownFrame.ClipsDescendants = true[span_105](end_span)
        [span_106](start_span)DropdownFrame.Parent = Container[span_106](end_span)

        [span_107](start_span)Instance.new("UICorner", DropdownFrame).CornerRadius = UDim.new(0, 5)[span_107](end_span)
        [span_108](start_span)local UIStroke = Instance.new("UIStroke", DropdownFrame)[span_108](end_span)
        [span_109](start_span)UIStroke.Color = Color3.fromRGB(0, 100, 150)[span_109](end_span)
        [span_110](start_span)UIStroke.Thickness = 1[span_110](end_span)

        [span_111](start_span)local TitleBtn = Instance.new("TextButton")[span_111](end_span)
        [span_112](start_span)TitleBtn.Size = UDim2.new(1, 0, 0, 35)[span_112](end_span)
        [span_113](start_span)TitleBtn.BackgroundTransparency = 1[span_113](end_span)
        [span_114](start_span)TitleBtn.Text = Text .. " ▼"[span_114](end_span)
        [span_115](start_span)TitleBtn.TextColor3 = Color3.fromRGB(255, 255, 255)[span_115](end_span)
        [span_116](start_span)TitleBtn.Font = Enum.Font.GothamBold[span_116](end_span)
        [span_117](start_span)TitleBtn.TextSize = 12[span_117](end_span)
        [span_118](start_span)TitleBtn.Parent = DropdownFrame[span_118](end_span)

        [span_119](start_span)local DropdownList = Instance.new("ScrollingFrame")[span_119](end_span)
        [span_120](start_span)DropdownList.Size = UDim2.new(1, -10, 1, -40)[span_120](end_span)
        [span_121](start_span)DropdownList.Position = UDim2.new(0, 5, 0, 35)[span_121](end_span)
        [span_122](start_span)DropdownList.BackgroundTransparency = 1[span_122](end_span)
        [span_123](start_span)DropdownList.ScrollBarThickness = 2[span_123](end_span)
        [span_124](start_span)DropdownList.Parent = DropdownFrame[span_124](end_span)

        [span_125](start_span)local ListLayout = Instance.new("UIListLayout", DropdownList)[span_125](end_span)
        [span_126](start_span)ListLayout.Padding = UDim.new(0, 4)[span_126](end_span)
        [span_127](start_span)ListLayout.HorizontalAlignment = Enum.HorizontalAlignment.Center[span_127](end_span)

        [span_128](start_span)local isOpen = false[span_128](end_span)
        [span_129](start_span)TitleBtn.MouseButton1Click:Connect(function()[span_129](end_span)
            [span_130](start_span)isOpen = not isOpen[span_130](end_span)
            [span_131](start_span)if isOpen then[span_131](end_span)
                [span_132](start_span)DropdownFrame.Size = UDim2.new(1, -10, 0, 140)[span_132](end_span)
                [span_133](start_span)TitleBtn.Text = Text .. " ▲"[span_133](end_span)
            [span_134](start_span)else[span_134](end_span)
                [span_135](start_span)DropdownFrame.Size = UDim2.new(1, -10, 0, 35)[span_135](end_span)
                [span_136](start_span)TitleBtn.Text = Text .. " ▼"[span_136](end_span)
            [span_137](start_span)end[span_137](end_span)
        [span_138](start_span)end)[span_138](end_span)

        [span_139](start_span)for _, option in ipairs(Options) do[span_139](end_span)
            [span_140](start_span)local OptBtn = Instance.new("TextButton")[span_140](end_span)
            [span_141](start_span)OptBtn.Size = UDim2.new(1, 0, 0, 25)[span_141](end_span)
            [span_142](start_span)OptBtn.BackgroundColor3 = Color3.fromRGB(45, 45, 45)[span_142](end_span)
            [span_143](start_span)OptBtn.Text = option[span_143](end_span)
            [span_144](start_span)OptBtn.TextColor3 = Color3.fromRGB(200, 200, 200)[span_144](end_span)
            [span_145](start_span)OptBtn.Font = Enum.Font.Gotham[span_145](end_span)
            [span_146](start_span)OptBtn.TextSize = 12[span_146](end_span)
            [span_147](start_span)OptBtn.Parent = DropdownList[span_147](end_span)
            [span_148](start_span)Instance.new("UICorner", OptBtn).CornerRadius = UDim.new(0, 4)[span_148](end_span)

            [span_149](start_span)OptBtn.MouseButton1Click:Connect(function()[span_149](end_span)
                [span_150](start_span)TitleBtn.Text = Text .. " : " .. option[span_150](end_span)
                [span_151](start_span)isOpen = false[span_151](end_span)
                [span_152](start_span)DropdownFrame.Size = UDim2.new(1, -10, 0, 35)[span_152](end_span)
                [span_153](start_span)pcall(Callback, option)[span_153](end_span)
            [span_154](start_span)end)[span_154](end_span)
        [span_155](start_span)end[span_155](end_span)

        [span_156](start_span)ListLayout:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()[span_156](end_span)
            [span_157](start_span)DropdownList.CanvasSize = UDim2.new(0, 0, 0, ListLayout.AbsoluteContentSize.Y)[span_157](end_span)
        [span_158](start_span)end)[span_158](end_span)
    [span_159](start_span)end[span_159](end_span)

    [span_160](start_span)function WindowElements:AddToggle(Text, DefaultState, Callback)[span_160](end_span)
        [span_161](start_span)local state = DefaultState or false[span_161](end_span)
        [span_162](start_span)local ToggleBtn = Instance.new("TextButton")[span_162](end_span)
        [span_163](start_span)ToggleBtn.Size = UDim2.new(1, -10, 0, 35)[span_163](end_span)
        [span_164](start_span)ToggleBtn.BackgroundColor3 = Color3.fromRGB(30, 30, 30)[span_164](end_span)
        [span_165](start_span)ToggleBtn.Font = Enum.Font.GothamBold[span_165](end_span)
        [span_166](start_span)ToggleBtn.TextSize = 13[span_166](end_span)
        [span_167](start_span)ToggleBtn.Parent = Container[span_167](end_span)

        [span_168](start_span)local function UpdateVisuals()[span_168](end_span)
            [span_169](start_span)ToggleBtn.Text = Text .. (state and " [ON]" or " [OFF]")[span_169](end_span)
            [span_170](start_span)ToggleBtn.TextColor3 = state and Color3.fromRGB(0, 255, 100) or Color3.fromRGB(255, 100, 100)[span_170](end_span)
        [span_171](start_span)end[span_171](end_span)
        [span_172](start_span)UpdateVisuals()[span_172](end_span)

        [span_173](start_span)Instance.new("UICorner", ToggleBtn).CornerRadius = UDim.new(0, 5)[span_173](end_span)
        [span_174](start_span)local ToggleStroke = Instance.new("UIStroke", ToggleBtn)[span_174](end_span)
        [span_175](start_span)ToggleStroke.Color = Color3.fromRGB(0, 100, 150)[span_175](end_span)
        [span_176](start_span)ToggleStroke.Thickness = 1[span_176](end_span)

        [span_177](start_span)ToggleBtn.MouseButton1Click:Connect(function()[span_177](end_span)
            [span_178](start_span)state = not state[span_178](end_span)
            [span_179](start_span)UpdateVisuals()[span_179](end_span)
            [span_180](start_span)pcall(Callback, state)[span_180](end_span)
        [span_181](start_span)end)[span_181](end_span)

        [span_182](start_span)local ToggleHandler = {}[span_182](end_span)
        [span_183](start_span)function ToggleHandler:Set(Value)[span_183](end_span)
            [span_184](start_span)state = Value[span_184](end_span)
            [span_185](start_span)UpdateVisuals()[span_185](end_span)
        [span_186](start_span)end[span_186](end_span)
        [span_187](start_span)return ToggleHandler[span_187](end_span)
    [span_188](start_span)end[span_188](end_span)

    [span_189](start_span)function WindowElements:AddButton(Text, Callback)[span_189](end_span)
        [span_190](start_span)local Btn = Instance.new("TextButton")[span_190](end_span)
        [span_191](start_span)Btn.Size = UDim2.new(1, -10, 0, 35)[span_191](end_span)
        [span_192](start_span)Btn.BackgroundColor3 = Color3.fromRGB(0, 100, 180)[span_192](end_span)
        [span_193](start_span)Btn.Text = Text[span_193](end_span)
        [span_194](start_span)Btn.TextColor3 = Color3.fromRGB(255, 255, 255)[span_194](end_span)
        [span_195](start_span)Btn.Font = Enum.Font.GothamBold[span_195](end_span)
        [span_196](start_span)Btn.TextSize = 13[span_196](end_span)
        [span_197](start_span)Btn.Parent = Container[span_197](end_span)

        [span_198](start_span)Instance.new("UICorner", Btn).CornerRadius = UDim.new(0, 5)[span_198](end_span)

        [span_199](start_span)Btn.MouseButton1Click:Connect(function()[span_199](end_span)
            [span_200](start_span)Btn.Text = "Loading..."[span_200](end_span)
            [span_201](start_span)task.spawn(function()[span_201](end_span)
                [span_202](start_span)pcall(Callback)[span_202](end_span)
                [span_203](start_span)task.wait(0.5)[span_203](end_span)
                [span_204](start_span)Btn.Text = Text[span_204](end_span)
            [span_205](start_span)end)[span_205](end_span)
        [span_206](start_span)end)[span_206](end_span)
    [span_207](start_span)end[span_207](end_span)

    [span_208](start_span)function WindowElements:AddInput(Text, Placeholder, Callback)[span_208](end_span)
        [span_209](start_span)local InputFrame = Instance.new("Frame")[span_209](end_span)
        [span_210](start_span)InputFrame.Size = UDim2.new(1, -10, 0, 40)[span_210](end_span)
        [span_211](start_span)InputFrame.BackgroundColor3 = Color3.fromRGB(30, 30, 30)[span_211](end_span)
        [span_212](start_span)InputFrame.Parent = Container[span_212](end_span)

        [span_213](start_span)Instance.new("UICorner", InputFrame).CornerRadius = UDim.new(0, 5)[span_213](end_span)
        [span_214](start_span)local InputStroke = Instance.new("UIStroke", InputFrame)[span_214](end_span)
        [span_215](start_span)InputStroke.Color = Color3.fromRGB(0, 100, 150)[span_215](end_span)
        [span_216](start_span)InputStroke.Thickness = 1[span_216](end_span)

        [span_217](start_span)local Label = Instance.new("TextLabel")[span_217](end_span)
        [span_218](start_span)Label.Size = UDim2.new(0.5, 0, 1, 0)[span_218](end_span)
        [span_219](start_span)Label.Position = UDim2.new(0, 10, 0, 0)[span_219](end_span)
        [span_220](start_span)Label.BackgroundTransparency = 1[span_220](end_span)
        [span_221](start_span)Label.Text = Text[span_221](end_span)
        [span_222](start_span)Label.TextColor3 = Color3.fromRGB(255, 255, 255)[span_222](end_span)
        [span_223](start_span)Label.Font = Enum.Font.GothamBold[span_223](end_span)
        [span_224](start_span)Label.TextSize = 12[span_224](end_span)
        [span_225](start_span)Label.TextXAlignment = Enum.TextXAlignment.Left[span_225](end_span)
        [span_226](start_span)Label.Parent = InputFrame[span_226](end_span)

        [span_227](start_span)local TextBox = Instance.new("TextBox")[span_227](end_span)
        [span_228](start_span)TextBox.Size = UDim2.new(0.4, 0, 0, 26)[span_228](end_span)
        [span_229](start_span)TextBox.Position = UDim2.new(0.6, -5, 0.5, -13)[span_229](end_span)
        [span_230](start_span)TextBox.BackgroundColor3 = Color3.fromRGB(15, 15, 15)[span_230](end_span)
        [span_231](start_span)TextBox.Text = ""[span_231](end_span)
        [span_232](start_span)TextBox.PlaceholderText = Placeholder or "Ketik..."[span_232](end_span)
        [span_233](start_span)TextBox.PlaceholderColor3 = Color3.fromRGB(100, 100, 100)[span_233](end_span)
        [span_234](start_span)TextBox.TextColor3 = Color3.fromRGB(0, 170, 255)[span_234](end_span)
        [span_235](start_span)TextBox.Font = Enum.Font.GothamBold[span_235](end_span)
        [span_236](start_span)TextBox.TextSize = 12[span_236](end_span)
        [span_237](start_span)TextBox.ClearTextOnFocus = true[span_237](end_span)
        [span_238](start_span)TextBox.Parent = InputFrame[span_238](end_span)

        [span_239](start_span)Instance.new("UICorner", TextBox).CornerRadius = UDim.new(0, 4)[span_239](end_span)

        [span_240](start_span)TextBox.FocusLost:Connect(function(enterPressed)[span_240](end_span)
            [span_241](start_span)pcall(Callback, TextBox.Text)[span_241](end_span)
        [span_242](start_span)end)[span_242](end_span)
        
        [span_243](start_span)local InputHandler = {}[span_243](end_span)
        [span_244](start_span)function InputHandler:Set(NewText)[span_244](end_span)
            [span_245](start_span)TextBox.Text = NewText[span_245](end_span)
        [span_246](start_span)end[span_246](end_span)
        [span_247](start_span)return InputHandler[span_247](end_span)
    [span_248](start_span)end[span_248](end_span)

    [span_249](start_span)function WindowElements:AddMultiDropdown(Text, Options, Callback)[span_249](end_span)
        [span_250](start_span)local DropdownFrame = Instance.new("Frame")[span_250](end_span)
        [span_251](start_span)DropdownFrame.Size = UDim2.new(1, -10, 0, 35)[span_251](end_span)
        [span_252](start_span)DropdownFrame.BackgroundColor3 = Color3.fromRGB(30, 30, 30)[span_252](end_span)
        [span_253](start_span)DropdownFrame.ClipsDescendants = true[span_253](end_span)
        [span_254](start_span)DropdownFrame.Parent = Container[span_254](end_span)

        [span_255](start_span)Instance.new("UICorner", DropdownFrame).CornerRadius = UDim.new(0, 5)[span_255](end_span)
        [span_256](start_span)local UIStroke = Instance.new("UIStroke", DropdownFrame)[span_256](end_span)
        [span_257](start_span)UIStroke.Color = Color3.fromRGB(0, 100, 150)[span_257](end_span)
        [span_258](start_span)UIStroke.Thickness = 1[span_258](end_span)

        [span_259](start_span)local TitleBtn = Instance.new("TextButton")[span_259](end_span)
        [span_260](start_span)TitleBtn.Size = UDim2.new(1, 0, 0, 35)[span_260](end_span)
        [span_261](start_span)TitleBtn.BackgroundTransparency = 1[span_261](end_span)
        [span_262](start_span)TitleBtn.Text = Text .. " ▼"[span_262](end_span)
        [span_263](start_span)TitleBtn.TextColor3 = Color3.fromRGB(255, 255, 255)[span_263](end_span)
        [span_264](start_span)TitleBtn.Font = Enum.Font.GothamBold[span_264](end_span)
        [span_265](start_span)TitleBtn.TextSize = 12[span_265](end_span)
        [span_266](start_span)TitleBtn.Parent = DropdownFrame[span_266](end_span)

        [span_267](start_span)local DropdownList = Instance.new("ScrollingFrame")[span_267](end_span)
        [span_268](start_span)DropdownList.Size = UDim2.new(1, -10, 1, -40)[span_268](end_span)
        [span_269](start_span)DropdownList.Position = UDim2.new(0, 5, 0, 35)[span_269](end_span)
        [span_270](start_span)DropdownList.BackgroundTransparency = 1[span_270](end_span)
        [span_271](start_span)DropdownList.ScrollBarThickness = 2[span_271](end_span)
        [span_272](start_span)DropdownList.Parent = DropdownFrame[span_272](end_span)

        [span_273](start_span)local ListLayout = Instance.new("UIListLayout", DropdownList)[span_273](end_span)
        [span_274](start_span)ListLayout.Padding = UDim.new(0, 4)[span_274](end_span)
        [span_275](start_span)ListLayout.HorizontalAlignment = Enum.HorizontalAlignment.Center[span_275](end_span)

        [span_276](start_span)local isOpen = false[span_276](end_span)
        [span_277](start_span)TitleBtn.MouseButton1Click:Connect(function()[span_277](end_span)
            [span_278](start_span)isOpen = not isOpen[span_278](end_span)
            [span_279](start_span)if isOpen then[span_279](end_span)
                [span_280](start_span)DropdownFrame.Size = UDim2.new(1, -10, 0, 140)[span_280](end_span)
                [span_281](start_span)TitleBtn.Text = Text .. " ▲"[span_281](end_span)
            [span_282](start_span)else[span_282](end_span)
                [span_283](start_span)DropdownFrame.Size = UDim2.new(1, -10, 0, 35)[span_283](end_span)
                [span_284](start_span)TitleBtn.Text = Text .. " ▼"[span_284](end_span)
            [span_285](start_span)end[span_285](end_span)
        [span_286](start_span)end)[span_286](end_span)

        [span_287](start_span)local SelectedOptions = {}[span_287](end_span)

        [span_288](start_span)for _, option in ipairs(Options) do[span_288](end_span)
            [span_289](start_span)SelectedOptions[option] = false[span_289](end_span)

            [span_290](start_span)local OptBtn = Instance.new("TextButton")[span_290](end_span)
            [span_291](start_span)OptBtn.Size = UDim2.new(1, 0, 0, 25)[span_291](end_span)
            [span_292](start_span)OptBtn.BackgroundColor3 = Color3.fromRGB(45, 45, 45)[span_292](end_span)
            [span_293](start_span)OptBtn.Text = option[span_293](end_span)
            [span_294](start_span)OptBtn.TextColor3 = Color3.fromRGB(200, 200, 200)[span_294](end_span)
            [span_295](start_span)OptBtn.Font = Enum.Font.Gotham[span_295](end_span)
            [span_296](start_span)OptBtn.TextSize = 12[span_296](end_span)
            [span_297](start_span)OptBtn.Parent = DropdownList[span_297](end_span)
            [span_298](start_span)Instance.new("UICorner", OptBtn).CornerRadius = UDim.new(0, 4)[span_298](end_span)

            [span_299](start_span)OptBtn.MouseButton1Click:Connect(function()[span_299](end_span)
                [span_300](start_span)SelectedOptions[option] = not SelectedOptions[option][span_300](end_span)
                
                [span_301](start_span)if SelectedOptions[option] then[span_301](end_span)
                    [span_302](start_span)OptBtn.Text = "✅ " .. option[span_302](end_span)
                    [span_303](start_span)OptBtn.TextColor3 = Color3.fromRGB(0, 255, 100)[span_303](end_span)
                [span_304](start_span)else[span_304](end_span)
                    [span_305](start_span)OptBtn.Text = option[span_305](end_span)
                    [span_306](start_span)OptBtn.TextColor3 = Color3.fromRGB(200, 200, 200)[span_306](end_span)
                [span_307](start_span)end[span_307](end_span)
                
                [span_308](start_span)pcall(Callback, SelectedOptions)[span_308](end_span)
            [span_309](start_span)end)[span_309](end_span)
        [span_310](start_span)end[span_310](end_span)

        [span_311](start_span)ListLayout:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()[span_311](end_span)
            [span_312](start_span)DropdownList.CanvasSize = UDim2.new(0, 0, 0, ListLayout.AbsoluteContentSize.Y)[span_312](end_span)
        [span_313](start_span)end)[span_313](end_span)
    [span_314](start_span)end[span_314](end_span)
    
    return WindowElements
end

return RZY_Library
